/**
 * @module view
 * Responsibilities: Encapsulate diagnostic page DOM, playback resource management, and localized result text without performing network requests or device capture.
 * Implementation: Update page controls and metrics through the provided document, and release temporary media URLs when replaced, cleared, or disposed.
 * Related Modules: app.js owns test lifecycle, media.js captures media, and i18n.js provides localized diagnostic copy.
 *
 * Declaration Index:
 * - DemoView.success.t: Reads success result text in current language.
 * - DemoView.failure.t: Reads failure result text in current language.
 * - DemoView.clear.t: Reads clear state text in current language.
 * - DemoView:
 *   Manages DOM display, busy state, and playback URL lifecycle of diagnostic page.
 * - DemoView.constructor:
 *   Initializes page state and releasable resources; only saves document reference, no access to persistent storage.
 * - DemoView.element:
 *   Retrieves the page's unique element by ID, serving as centralized DOM lookup to avoid scattered global dependencies.
 * - DemoView.log:
 *   Appends time-stamped diagnostic messages to the page, truncating old entries; does not write to console or files.
 * - DemoView.status:
 *   Sets accessible status text and error styling; error only controls presentation, not business state.
 * - DemoView.busy:
 *   Disables duplicate start and clear operations during testing; stop capture button is independently enabled by media controller.
 * - DemoView.busy.callback1:
 *   Enables or disables a test button based on test busy state, preventing duplicate starts.
 * - DemoView.progress:
 *   Displays cumulative count of verified fragments and RTT; does not count sent data as verified.
 * - DemoView.reset:
 *   Resets single-test metrics and releases previous playback, retaining limited page history logs.
 * - DemoView.preview:
 *   Passes MediaStream to local preview; passing null breaks element's reference to capture stream.
 * - DemoView.releasePlayback:
 *   Stops decoding, clears src, and revokes Blob URL, ensuring player does not retain old media.
 * - DemoView.playback:
 *   Receives fully validated media Blob from return transmission, creates a single temporary playback URL.
 * - DemoView.success:
 *   Displays server-side completion confirmation; uses distinct wording for ping and media validation to avoid misinterpretation from zero fragments.
 * - DemoView.failure:
 *   Displays failure and revokes potentially unconfirmed playback; does not trigger reconnection or retry.
 * - DemoView.clear:
 *   Clears current metrics, page logs, and composite canvas, proactively releasing visible test results.
 *
 * Variable Index:
 * None
 *
 * Key state explanation:
 * document is provided by caller; playbackUrl points to current playback at most, released upon replacement or page exit. Logs are retained only within the page, not written to console, file, or browser persistent storage; result texts generated by AppI18n based on current language.
 */
/**
 * Manages DOM display, busy state, and playback URL lifecycle of diagnostic page.
 */
export class DemoView {
  /**
 * Initializes page state and releasable resources; only saves document reference, no access to persistent storage.
 */
  constructor(document) {
    this.document = document;
    this.playbackUrl = null;
  }

  /**
 * Retrieves the page's unique element by ID, serving as centralized DOM lookup to avoid scattered global dependencies.
 */
  element(id) {
    return this.document.getElementById(id);
  }

  /**
 * Appends time-stamped diagnostic messages to the page, truncating old entries; does not write to console or files.
 */
  log(message) {
    const lines = this.element("log").textContent.split("\n").filter(Boolean);
    lines.push(`${new Date().toLocaleTimeString()}  ${message}`);
    this.element("log").textContent = lines.slice(-30).join("\n");
  }

  /**
 * Sets accessible status text and error styling; error only controls presentation, not business state.
 */
  status(text, error = false) {
    this.element("status").textContent = text;
    this.element("status").classList.toggle("error", error);
  }

  /**
 * Disables duplicate start and clear operations during testing; stop capture button is independently enabled by media controller.
 */
  busy(value) {
    /**
 * Enables or disables a test button based on test busy state, preventing duplicate starts.
 */
    this.document.querySelectorAll("[data-test]").forEach((button) => {
      button.disabled = value;
    });
    this.element("clear").disabled = value;
    this.element("stop").disabled = true;
  }

  /**
 * Displays cumulative count of verified fragments and RTT; does not count sent data as verified.
 */
  progress({ chunks, bytes, rttMs }) {
    this.element("chunks").textContent = String(chunks);
    this.element("bytes").textContent = String(bytes);
    this.element("latency").textContent = rttMs.toFixed(1);
  }

  /**
 * Resets single-test metrics and releases previous playback, retaining limited page history logs.
 */
  reset() {
    this.releasePlayback();
    this.element("chunks").textContent = "0";
    this.element("bytes").textContent = "0";
    this.element("latency").textContent = "—";
    this.element("summary").textContent = window.AppI18n?.t("stream_running") ?? "Test in progress…";
  }

  /**
 * Passes MediaStream to local preview; passing null breaks element's reference to capture stream.
 */
  preview(stream) {
    this.element("preview").srcObject = stream;
  }

  /**
 * Stops decoding, clears src, and revokes Blob URL, ensuring player does not retain old media.
 */
  releasePlayback() {
    const video = this.element("playback");
    video.pause();
    video.removeAttribute("src");
    video.load();
    if (this.playbackUrl) URL.revokeObjectURL(this.playbackUrl);
    this.playbackUrl = null;
  }

  /**
 * Receives fully validated media Blob from return transmission, creates a single temporary playback URL.
 */
  playback(blob) {
    this.releasePlayback();
    this.playbackUrl = URL.createObjectURL(blob);
    this.element("playback").src = this.playbackUrl;
  }

  /**
 * Displays server-side completion confirmation; uses distinct wording for ping and media validation to avoid misinterpretation from zero fragments.
 */
  success(mode, summary) {
    /**
 * Returns success result text in current language.
 */
    const t = (key, values = {}) => window.AppI18n?.t(key, values) ?? key;
    this.status(t("stream_pass"));
    this.element("summary").textContent = mode === "ping"
      ? t("stream_pass_ping")
      : t("stream_pass_media", { chunks: summary.chunk_count, bytes: summary.byte_count });
    this.log(t("stream_complete_log", { chunks: summary.chunk_count, bytes: summary.byte_count }));
  }

  /**
 * Displays failure and revokes potentially unconfirmed playback; does not trigger reconnection or retry.
 */
  failure(error) {
    /**
 * Returns failure result text in current language.
 */
    const t = (key, values = {}) => window.AppI18n?.t(key, values) ?? key;
    this.status(t("stream_failed"), true);
    this.element("summary").textContent = t("stream_fail_summary", { message: error.message });
    this.log(t("stream_fail_log", { message: error.message }));
    this.releasePlayback();
  }

  /**
 * Clears current metrics, page logs, and composite canvas, proactively releasing visible test results.
 */
  clear() {
    this.reset();
    this.element("source").getContext("2d").clearRect(0, 0, 640, 360);
    this.element("log").textContent = "";
    /**
 * Returns clear state text in current language.
 */
    const t = (key) => window.AppI18n?.t(key) ?? key;
    this.element("summary").textContent = t("stream_cleared");
    this.status(t("status_ready"));
  }
}
