"""历史初始 schema。保留已应用迁移的结构定义，后续迁移撤销诊断表而非改写历史。

目录：
- Migration：
  初始表与约束的历史声明；operations 由迁移引擎按顺序执行。

关键变量：
（无模块级变量。）

关键状态说明：
Migration.initial、dependencies、operations 描述历史建表顺序；其中旧 StreamProbe
由后续迁移删除，本文件只补充注释，不修改已应用的操作。
"""
# Generated by Django 5.2.17 on 2026-09-11 03:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """初始表与约束的历史声明；operations 由迁移引擎按顺序执行。"""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(max_length=4000)),
                ("position", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="StreamProbe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("finished", "Finished"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="connected",
                        max_length=16,
                    ),
                ),
                ("mode", models.CharField(blank=True, max_length=16)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("byte_count", models.PositiveBigIntegerField(default=0)),
                ("verified_chunks", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ["-started_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "prep_seconds",
                    models.PositiveIntegerField(default=10, editable=False),
                ),
                (
                    "answer_seconds",
                    models.PositiveIntegerField(default=90, editable=False),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("finished_at__isnull", True), ("status", "active")),
                            models.Q(("finished_at__isnull", False), ("status", "completed")),
                            _connector="OR",
                        ),
                        name="session_status_timestamp",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(max_length=4000)),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answering", "Answering"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("answer_text", models.TextField(blank=True, max_length=20000)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="interviews.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="interviews.practicesession",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "position"), name="unique_session_position"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "answering")),
                        fields=("session",),
                        name="one_answering_item",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finished_at__isnull", True),
                                ("started_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("finished_at__isnull", True),
                                ("started_at__isnull", False),
                                ("status", "answering"),
                            ),
                            models.Q(
                                ("finished_at__isnull", False),
                                ("started_at__isnull", False),
                                ("status", "completed"),
                            ),
                            models.Q(("finished_at__isnull", False), ("status", "skipped")),
                            _connector="OR",
                        ),
                        name="item_status_timestamps",
                    ),
                ],
            },
        ),
    ]
