"""Responsibilities: Remove the obsolete diagnostic storage table.
Implementation: Delete StreamProbe and its historical rows while preserving migration ordering.
Related Modules: The prior seed migration and Django's migration runner.
Declaration Index:
- Migration: Declare deletion of the obsolete StreamProbe table.
Variable Index:
None
"""
# Generated by Django 5.2.17 on 2026-09-11 04:49

from django.db import migrations


class Migration(migrations.Migration):
    """Functionality: Remove the historical StreamProbe table.
    Inputs: Database schema produced by the seed migration.
    Outputs: Deletes the obsolete table and its rows.
    Logic: Declare DeleteModel after migration 0002.
    Constraints: This operation is part of the established migration history.
    """

    dependencies = [
        ("interviews", "0002_seed_questions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StreamProbe",
        ),
    ]
