"""诊断存储移除迁移。删除旧测试表及记录，使最终 schema 只保留三张业务表。

目录：
- Migration：
  声明删除旧诊断表；已有数据库升级时清理历史测试统计。

关键变量：
（无模块级变量。）

关键状态说明：
Migration.dependencies 与 operations 保留历史顺序和删除操作；本轮不变更数据库 schema。
"""
# Generated by Django 5.2.17 on 2026-09-11 04:49

from django.db import migrations


class Migration(migrations.Migration):
    """声明删除旧诊断表；已有数据库升级时清理历史测试统计。"""

    dependencies = [
        ("interviews", "0002_seed_questions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StreamProbe",
        ),
    ]
