# Generated by Django 5.2.17 on 2026-10-09 09:18

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0011_merge_evaluation_automatic_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentShadowJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("base_state_version", models.PositiveIntegerField()),
                ("committed_state_version", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shadow_job",
                        to="interviews.agentanswer",
                    ),
                ),
                (
                    "feedback_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shadow_job",
                        to="interviews.agentrequest",
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_jobs",
                        to="interviews.agentinterview",
                    ),
                ),
            ],
            options={
                "ordering": ["committed_state_version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interview", "committed_state_version"),
                        name="shadow_job_turn_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "committed_state_version",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("base_state_version"), "+", models.Value(1)
                                ),
                            )
                        ),
                        name="shadow_job_base_version",
                    ),
                ],
            },
        ),
    ]
