# Generated by Django 5.2.17 on 2026-10-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0012_background_shadow_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="interviews.agentshadowjob",
                    ),
                ),
            ],
            options={
                "ordering": ["job__committed_state_version"],
            },
        ),
    ]
